---
- name: ngrok | ensure ngrok config folder exists
  become_user: "{{ ngrok_user }}"
  file:
    path: "/home/{{ ngrok_user }}/.ngrok2"
    owner: "{{ ngrok_user }}"
    state: directory

- name: ngrok | add tunnel configuration file
  become_user: "{{ ngrok_user }}"
  template:
    src: "ngrok.yml.j2"
    dest: "/home/{{ ngrok_user }}/.ngrok2/ngrok.yml"
    owner: "{{ ngrok_user }}"
    force: no
